# Generated by Django 5.1.6 on 2026-03-17 14:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.PositiveBigIntegerField(unique=True, verbose_name="ID РК"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название кампании"
                    ),
                ),
                (
                    "bid_type",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Тип ставки"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Тип оплаты"
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=32, verbose_name="Статус"),
                ),
                (
                    "monitoring_group",
                    models.CharField(
                        choices=[
                            ("unified", "Единая ставка"),
                            ("manual_search", "Руч. поиск"),
                            ("manual_shelves", "Руч. полки"),
                            ("manual_catalog", "Руч. каталог"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Группа мониторинга",
                    ),
                ),
                (
                    "placements",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Зоны показов"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырой ответ API"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Рекламная кампания",
                "verbose_name_plural": "Рекламные кампании",
                "ordering": ["name", "external_id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nm_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="Артикул WB"
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Артикул продавца"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(blank=True, max_length=128, verbose_name="Бренд"),
                ),
                (
                    "subject_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Предмет"
                    ),
                ),
                (
                    "buyout_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("24.00"),
                        max_digits=5,
                        verbose_name="Процент выкупа, %",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "logistics_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Логистика",
                    ),
                ),
                (
                    "primary_keyword",
                    models.CharField(blank=True, max_length=255, verbose_name="Ключ 1"),
                ),
                (
                    "secondary_keyword",
                    models.CharField(blank=True, max_length=255, verbose_name="Ключ 2"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["title", "nm_id"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("full", "Полная синхронизация"),
                            ("product", "Синхронизация товара"),
                            ("product_meta", "Обновление карточки товара"),
                            ("campaign_meta", "Обновление кампании"),
                        ],
                        default="full",
                        max_length=32,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "В работе"),
                            ("success", "Успешно"),
                            ("error", "Ошибка"),
                        ],
                        default="running",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Целевая дата"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Детали"),
                ),
            ],
            options={
                "verbose_name": "Лог синхронизации",
                "verbose_name_plural": "Логи синхронизации",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "office_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="ID склада"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Склад")),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Регион"),
                ),
                (
                    "is_visible_in_monitoring",
                    models.BooleanField(
                        default=True, verbose_name="Показывать в мониторинге"
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
                "ordering": ["name", "office_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_campaigns",
                        to="monitoring.campaign",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_campaigns",
                        to="monitoring.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь товара и РК",
                "verbose_name_plural": "Связи товара и РК",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                through="monitoring.ProductCampaign",
                to="monitoring.product",
            ),
        ),
        migrations.CreateModel(
            name="DailyWarehouseStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stats_date", models.DateField(verbose_name="Дата остатков")),
                (
                    "stock_count",
                    models.PositiveIntegerField(default=0, verbose_name="Остаток"),
                ),
                (
                    "in_way_to_client",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Едут к клиенту"
                    ),
                ),
                (
                    "in_way_from_client",
                    models.PositiveIntegerField(default=0, verbose_name="Возвращаются"),
                ),
                (
                    "avg_orders",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Средние заказы",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырой ответ API"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="monitoring.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_stocks",
                        to="monitoring.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневные остатки по складу",
                "verbose_name_plural": "Дневные остатки по складам",
                "ordering": ["warehouse__name", "product_id"],
            },
        ),
        migrations.CreateModel(
            name="DailyProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stats_date", models.DateField(verbose_name="Дата остатков")),
                (
                    "total_stock",
                    models.PositiveIntegerField(default=0, verbose_name="Остатки WB"),
                ),
                (
                    "in_way_to_client",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Едут к клиенту"
                    ),
                ),
                (
                    "in_way_from_client",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Возвращаются на склад"
                    ),
                ),
                (
                    "avg_orders_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Среднее заказов/день",
                    ),
                ),
                (
                    "days_until_zero",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Дней до нуля",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=16, verbose_name="Валюта"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырой ответ API"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stocks",
                        to="monitoring.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневные остатки товара",
                "verbose_name_plural": "Дневные остатки товаров",
                "ordering": ["-stats_date", "product_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "stats_date"),
                        name="uniq_daily_product_stock",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyProductNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note_date", models.DateField(verbose_name="Дата заметки")),
                (
                    "spp_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="СПП, %"
                    ),
                ),
                (
                    "seller_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Цена WBSELLER",
                    ),
                ),
                (
                    "wb_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Цена WB",
                    ),
                ),
                (
                    "promo_status",
                    models.CharField(blank=True, max_length=255, verbose_name="Акция"),
                ),
                (
                    "negative_feedback",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Негативные отзывы"
                    ),
                ),
                (
                    "unified_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Включили РК единая ставка"
                    ),
                ),
                (
                    "manual_search_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Включили РК руч. поиск"
                    ),
                ),
                (
                    "manual_shelves_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Включили РК руч. полки"
                    ),
                ),
                (
                    "price_changed",
                    models.BooleanField(default=False, verbose_name="Меняли цену"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_notes",
                        to="monitoring.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневная заметка",
                "verbose_name_plural": "Дневные заметки",
                "ordering": ["-note_date", "product_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "note_date"), name="uniq_daily_product_note"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyProductMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stats_date", models.DateField(verbose_name="Дата статистики")),
                (
                    "open_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Переходы в карточку"
                    ),
                ),
                (
                    "add_to_cart_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Добавления в корзину"
                    ),
                ),
                (
                    "order_count",
                    models.PositiveIntegerField(default=0, verbose_name="Заказы"),
                ),
                (
                    "order_sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Сумма заказов",
                    ),
                ),
                (
                    "buyout_count",
                    models.PositiveIntegerField(default=0, verbose_name="Выкупы"),
                ),
                (
                    "buyout_sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Сумма выкупов",
                    ),
                ),
                (
                    "add_to_wishlist_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Добавления в избранное"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=16, verbose_name="Валюта"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырой ответ API"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="monitoring.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневная воронка товара",
                "verbose_name_plural": "Дневные воронки товаров",
                "ordering": ["-stats_date", "product_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "stats_date"),
                        name="uniq_daily_product_metrics",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyCampaignProductStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stats_date", models.DateField(verbose_name="Дата статистики")),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("search", "Поиск"),
                            ("recommendation", "Полки"),
                            ("catalog", "Каталог"),
                            ("unknown", "Неизвестно"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="Зона показов",
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="Показы"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="Клики"),
                ),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Расход",
                    ),
                ),
                (
                    "add_to_cart_count",
                    models.PositiveIntegerField(default=0, verbose_name="Корзины"),
                ),
                (
                    "order_count",
                    models.PositiveIntegerField(default=0, verbose_name="Заказы"),
                ),
                (
                    "units_ordered",
                    models.PositiveIntegerField(default=0, verbose_name="ШК"),
                ),
                (
                    "order_sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Сумма заказов",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырой ответ API"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="monitoring.campaign",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_stats",
                        to="monitoring.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневная статистика РК по товару",
                "verbose_name_plural": "Дневные статистики РК по товарам",
                "ordering": ["-stats_date", "campaign_id", "product_id", "zone"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "product", "stats_date", "zone"),
                        name="uniq_campaign_product_zone_day",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productcampaign",
            constraint=models.UniqueConstraint(
                fields=("product", "campaign"), name="uniq_product_campaign"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailywarehousestock",
            constraint=models.UniqueConstraint(
                fields=("product", "warehouse", "stats_date"),
                name="uniq_daily_warehouse_stock",
            ),
        ),
    ]
