# Generated by Django 5.1.6 on 2026-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_name",
                    models.CharField(
                        default="Мониторинг WB",
                        max_length=255,
                        verbose_name="Название проекта",
                    ),
                ),
                (
                    "report_timezone",
                    models.CharField(
                        default="Asia/Bishkek",
                        max_length=64,
                        verbose_name="Часовой пояс отчётов",
                    ),
                ),
                (
                    "sync_hour",
                    models.PositiveSmallIntegerField(
                        default=9, verbose_name="Час ежедневной синхронизации"
                    ),
                ),
                (
                    "sync_minute",
                    models.PositiveSmallIntegerField(
                        default=15, verbose_name="Минута ежедневной синхронизации"
                    ),
                ),
                (
                    "overwrite_within_day",
                    models.BooleanField(
                        default=True,
                        verbose_name="Перезаписывать данные в рамках суток",
                    ),
                ),
                (
                    "visible_warehouses_note",
                    models.TextField(blank=True, verbose_name="Комментарий по складам"),
                ),
                (
                    "campaign_grouping_note",
                    models.TextField(
                        blank=True, verbose_name="Комментарий по группировке РК"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки мониторинга",
                "verbose_name_plural": "Настройки мониторинга",
            },
        ),
    ]
