# Generated by Django 5.1.6 on 2026-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_monitoringsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringsettings",
            name="google_dashboard_sheet_name",
            field=models.CharField(
                default="Dashboard", max_length=100, verbose_name="Лист сводки"
            ),
        ),
        migrations.AddField(
            model_name="monitoringsettings",
            name="google_sheets_auto_sync",
            field=models.BooleanField(
                default=True, verbose_name="Автообновление Google Sheets после WB sync"
            ),
        ),
        migrations.AddField(
            model_name="monitoringsettings",
            name="google_sheets_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Включить Google Sheets"
            ),
        ),
        migrations.AddField(
            model_name="monitoringsettings",
            name="google_spreadsheet_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID Google таблицы"
            ),
        ),
    ]
