# Generated by Django 5.1.6 on 2026-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_monitoringsettings_google_dashboard_sheet_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringsettings",
            name="monitoring_history_days",
            field=models.PositiveSmallIntegerField(
                default=14, verbose_name="Дней в мониторинге"
            ),
        ),
    ]
