# Generated by Django 5.1.6 on 2026-03-18 15:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone


def seed_product_economics_versions(apps, schema_editor):
    Product = apps.get_model("monitoring", "Product")
    ProductEconomicsVersion = apps.get_model("monitoring", "ProductEconomicsVersion")
    for product in Product.objects.all():
        effective_from = product.created_at.date() if product.created_at else timezone.localdate()
        ProductEconomicsVersion.objects.get_or_create(
            product=product,
            effective_from=effective_from,
            defaults={
                "buyout_percent": product.buyout_percent,
                "unit_cost": product.unit_cost,
                "logistics_cost": product.logistics_cost,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_monitoringsettings_monitoring_history_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductEconomicsVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(verbose_name="Действует с")),
                (
                    "buyout_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("24.00"),
                        max_digits=5,
                        verbose_name="Процент выкупа, %",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "logistics_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Логистика",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economics_versions",
                        to="monitoring.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия экономики товара",
                "verbose_name_plural": "Версии экономики товаров",
                "ordering": ["product_id", "-effective_from", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "effective_from"),
                        name="uniq_product_economics_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductVisibleWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warehouse_name",
                    models.CharField(max_length=255, verbose_name="Склад показа"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visible_warehouse_rules",
                        to="monitoring.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад показа для товара",
                "verbose_name_plural": "Склады показа для товаров",
                "ordering": ["product_id", "warehouse_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "warehouse_name"),
                        name="uniq_product_visible_warehouse",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_product_economics_versions, migrations.RunPython.noop),
    ]
