# Generated by Django 5.1.6 on 2026-03-20 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_producteconomicsversion_productvisiblewarehouse"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProductKeywordStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stats_date",
                    models.DateField(verbose_name="Р”Р°С‚Р° СЃС‚Р°С‚РёСЃС‚РёРєРё"),
                ),
                (
                    "query_text",
                    models.CharField(
                        max_length=255, verbose_name="РџРѕРёСЃРєРѕРІС‹Р№ Р·Р°РїСЂРѕСЃ"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Р§Р°СЃС‚РѕС‚Р°"
                    ),
                ),
                (
                    "organic_position",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="РџРѕР·РёС†РёСЏ РѕСЂРіР°РЅРёРєРё",
                    ),
                ),
                (
                    "organic_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Р—Р°РєР°Р·С‹ РѕСЂРіР°РЅРёРєРё"
                    ),
                ),
                (
                    "boosted_position",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="РџРѕР·РёС†РёСЏ Р±СѓСЃС‚Р°",
                    ),
                ),
                (
                    "boosted_ctr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="CTR Р±СѓСЃС‚Р°",
                    ),
                ),
                (
                    "boosted_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="РџРѕРєР°Р·С‹ Р±СѓСЃС‚Р°"
                    ),
                ),
                (
                    "boosted_clicks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="РљР»РёРєРё Р±СѓСЃС‚Р°"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="РЎС‹СЂРѕР№ РѕС‚РІРµС‚ API",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_keyword_stats",
                        to="monitoring.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Р”РЅРµРІРЅР°СЏ РјРµС‚СЂРёРєР° РєР»СЋС‡Р°",
                "verbose_name_plural": "Р”РЅРµРІРЅС‹Рµ РјРµС‚СЂРёРєРё РєР»СЋС‡РµР№",
                "ordering": ["-stats_date", "product_id", "query_text"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "stats_date", "query_text"),
                        name="uniq_daily_product_keyword_stat",
                    )
                ],
            },
        ),
    ]
