# Generated by Django 5.1.6 on 2026-03-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_dailycampaignsearchclusterstat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoringsettings",
            name="google_dashboard_sheet_name",
        ),
        migrations.RemoveField(
            model_name="monitoringsettings",
            name="google_sheets_auto_sync",
        ),
        migrations.RemoveField(
            model_name="monitoringsettings",
            name="google_sheets_enabled",
        ),
        migrations.RemoveField(
            model_name="monitoringsettings",
            name="google_spreadsheet_id",
        ),
    ]
