# Generated by Django 5.1.6 on 2026-04-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0008_productkeyword"),
        ("monitoring", "0008_remove_monitoringsettings_google_fields"),
    ]

    operations = []
