# Generated by Django 5.1.6 on 2026-04-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0010_add_dailyproductnote_keywords"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyproductkeywordstat",
            options={
                "ordering": ["-stats_date", "product_id", "query_text"],
                "verbose_name": "Дневная метрика ключа",
                "verbose_name_plural": "Дневные метрики ключей",
            },
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="boosted_clicks",
            field=models.PositiveIntegerField(default=0, verbose_name="Клики буста"),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="boosted_ctr",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="CTR буста"
            ),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="boosted_position",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Позиция буста"
            ),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="boosted_views",
            field=models.PositiveIntegerField(default=0, verbose_name="Показы буста"),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="frequency",
            field=models.PositiveIntegerField(default=0, verbose_name="Частота"),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="organic_orders",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Заказы органики"
            ),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="organic_position",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Позиция органики",
            ),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="query_text",
            field=models.CharField(max_length=255, verbose_name="Поисковый запрос"),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="raw_payload",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Сырой ответ API"
            ),
        ),
        migrations.AlterField(
            model_name="dailyproductkeywordstat",
            name="stats_date",
            field=models.DateField(verbose_name="Дата статистики"),
        ),
        migrations.AlterField(
            model_name="productkeyword",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="productkeyword",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "В работе"),
                    ("success", "Успешно"),
                    ("error", "Ошибка"),
                    ("canceled", "Отменено"),
                ],
                default="running",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
    ]
