# Generated by Django 5.1.6 on 2026-04-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0015_remove_monitoringsettings_overwrite_within_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycampaignsearchclusterstat",
            name="order_sum",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="Сумма заказов"
            ),
        ),
    ]
